#!/bin/bash

selected="$(ps -a -u $USER | \
			dmenu -i -p "Type to search and select process to kill" -l 20 | \
			awk '{print $1" "$4}')";

if [[ ! -z $selected ]]; then

	answer="$(echo -e "Yes\nNo" | \
			dmenu -i -p "$selected will be killed, are you sure?" -l 20 )"

	if [[ $answer == "Yes" ]]; then
		selpid="$(awk '{print $1}' <<< $selected)";
		kill -9 $selpid
	fi
fi

exit 0
